using System.Text.Json.Serialization;

namespace Shark.Fido2.Models.Responses;

/// <summary>
/// Public key credential get options response.
/// </summary>
// See: https://fidoalliance.org/specs/fido-v2.0-rd-20180702/fido-server-v2.0-rd-20180702.html#serverpublickeycredentialgetoptionsresponse.
public sealed class ServerPublicKeyCredentialGetOptionsResponse : ServerResponse
{
    /// <summary>
    /// Gets the cryptographic challenge generated by the server.
    /// </summary>
    [JsonPropertyName("challenge")]
    public required string Challenge { get; init; }

    /// <summary>
    /// Gets the expiry timeout in milliseconds.
    /// </summary>
    [JsonPropertyName("timeout")]
    public ulong? Timeout { get; init; }

    /// <summary>
    /// Gets the Relying Party identifier (RP ID).
    /// </summary>
    [JsonPropertyName("rpId")]
    public string? RpId { get; init; }

    /// <summary>
    /// Gets the list of credential descriptors indicating which credentials the server allows for authentication.
    /// </summary>
    [JsonPropertyName("allowCredentials")]
    public required ServerPublicKeyCredentialDescriptor[] AllowCredentials { get; init; }

    /// <summary>
    /// Gets the Relying Party's requirement for user verification.
    /// </summary>
    [JsonPropertyName("userVerification")]
    public required string UserVerification { get; init; }

    /// <summary>
    /// Gets the requested client extensions.
    /// </summary>
    [JsonPropertyName("extensions")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public ServerAuthenticationExtensionsClientInputs? Extensions { get; init; }
}
