using System.Text.Json.Serialization;

namespace Shark.Fido2.Models.Responses;

/// <summary>
/// Public key credential creation options response.
/// </summary>
// See: https://fidoalliance.org/specs/fido-v2.0-rd-20180702/fido-server-v2.0-rd-20180702.html#serverpublickeycredentialcreationoptionsresponse.
public sealed class ServerPublicKeyCredentialCreationOptionsResponse : ServerResponse
{
    /// <summary>
    /// Gets the Relying Party entity information.
    /// </summary>
    [JsonPropertyName("rp")]
    public required ServerPublicKeyCredentialRpEntity RelyingParty { get; init; }

    /// <summary>
    /// Gets the user entity information.
    /// </summary>
    [JsonPropertyName("user")]
    public required ServerPublicKeyCredentialUserEntity User { get; init; }

    /// <summary>
    /// Gets the public key credential parameters (supported algorithms).
    /// </summary>
    [JsonPropertyName("pubKeyCredParams")]
    public required ServerPublicKeyCredentialParameters[] Parameters { get; init; }

    /// <summary>
    /// Gets the cryptographic challenge generated by the server.
    /// </summary>
    [JsonPropertyName("challenge")]
    public required string Challenge { get; init; }

    /// <summary>
    /// Gets the expiry timeout in milliseconds.
    /// </summary>
    [JsonPropertyName("timeout")]
    public ulong Timeout { get; init; }

    /// <summary>
    /// Gets a list of credentials to exclude to avoid re-registering the same authenticator.
    /// </summary>
    [JsonPropertyName("excludeCredentials")]
    public required ServerPublicKeyCredentialDescriptor[] ExcludeCredentials { get; init; }

    /// <summary>
    /// Gets the authenticator selection criteria.
    /// </summary>
    [JsonPropertyName("authenticatorSelection")]
    public required ServerAuthenticatorSelectionCriteria AuthenticatorSelection { get; init; }

    /// <summary>
    /// Gets the preferred attestation conveyance preference.
    /// </summary>
    [JsonPropertyName("attestation")]
    public required string Attestation { get; init; }

    /// <summary>
    /// Gets the requested client extensions.
    /// </summary>
    [JsonPropertyName("extensions")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public ServerAuthenticationExtensionsClientInputs? Extensions { get; init; }
}
