name: Build Docker image

permissions:
  contents: read

on:
  workflow_dispatch:
  schedule:
    - cron: '0 21 * * 0' # Run every Sunday at 21:00 UTC

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 #v4.1.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - uses: actions/checkout@v6
    - name: Build and push Docker image
      env:
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      run: |
        docker build . --file ./src/Shark.Fido2.Sample/Dockerfile \
          --tag $DOCKERHUB_USERNAME/shark-fido2-sample:latest \
          --tag $DOCKERHUB_USERNAME/shark-fido2-sample:v1.4.0
        docker push $DOCKERHUB_USERNAME/shark-fido2-sample:latest
        docker push $DOCKERHUB_USERNAME/shark-fido2-sample:v1.4.0
