name: build_push_nuget_sdk

on:
  push:
    branches:
      - main
      - feature/nuget-**
    paths:
      - src/Shark.Fido2.Common/**
      - src/Shark.Fido2.Core/**
      - src/Shark.Fido2.Domain/**
      - src/Shark.Fido2.Metadata.Core/**
      - src/Shark.Fido2.Metadata.Domain/**
      - src/Shark.Fido2.Models/**
      - src/Shark.Fido2.Repositories.InMemory/**
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore ./src/Shark.Fido2.Core/Shark.Fido2.Core.csproj

    - name: Build with dotnet
      run: dotnet build ./src/Shark.Fido2.Core/Shark.Fido2.Core.csproj --configuration Release --no-restore

    - name: Pack with dotnet
      run: dotnet pack ./src/Shark.Fido2.Core/Shark.Fido2.Core.csproj --configuration Release --no-restore --output ./nupkg /p:Version=0.0."${{ github.run_number }}"

    - name: Add nuget source
      run: dotnet nuget add source --username linuxchata --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/linuxchata/index.json"

    - name: Push nuget to github.com
      run: dotnet nuget push "./nupkg/Shark.Fido2.Core.*.nupkg" --api-key ${{ secrets.OAUTH_GITHUB_PAT }} --source "github" --skip-duplicate

    - name: Push nuget to nuget.org
      run: dotnet nuget push "./nupkg/Shark.Fido2.Core.*.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
