name: Performance

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore ./src/Shark.Fido2.sln

    - name: Build
      run: dotnet build ./src/Shark.Fido2.sln --configuration Release --no-restore

    - name: Test
      run: dotnet test ./src/Shark.Fido2.sln --filter FullyQualifiedName=Shark.Fido2.Core.Performance.Tests --configuration Release --no-build --verbosity normal

    - name: Check for performance reports
      id: check-reports
      run: |
        if [ -d "nbomber_reports" ] && [ "$(ls -A nbomber_reports)" ]; then
          echo "reports-exist=true" >> $GITHUB_OUTPUT
          echo "Performance reports found in nbomber_reports/"
        else
          echo "reports-exist=false" >> $GITHUB_OUTPUT
          echo "No performance reports found"
        fi

    - name: Upload Test Results as Artifact
      if: steps.check-reports.outputs.reports-exist == 'true'
      uses: actions/upload-artifact@v4
      with:
        name: performance-test-results
        path: nbomber_reports/
