name: Performance

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore ./src/Shark.Fido2.sln

    - name: Build
      run: dotnet build ./src/Shark.Fido2.sln --configuration Release --no-restore

    - name: Test
      run: dotnet test ./src/Shark.Fido2.sln --filter FullyQualifiedName\=Shark.Fido2.Core.Performance.Tests --configuration Release --no-build --verbosity normal

    - name: Upload Test Results as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: nbomber_reports/
